resources:
  - name: gatling
    type: git
    source:
      uri: https://github.com/Sparsh79/GatlingDEMO.git
      branch: master

jobs:
  - name: gatling-test
    serial: true
    plan:
      - get: gatling
        trigger: true
      - task: run-test
        privileged: true
        file: gatling/test.yml